# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: my-backend

on: workflow_dispatch
jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Get list file
      run: ls -la

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      run: go test -v ./...
  build:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Get dependencies
        run: go mod tidy
      - name: Build Binary
        run: go build -o http-server -v cmd/main.go
      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: ./http-server
  build-container:
    needs: build
    runs-on: self-hosted
    steps:
      - name: load artifact
        uses: actions/download-artifact@v3
        with:
          name: my-app
      - name: List files
        run: ls -la
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/http-server:0.0.${{ github.run_number }}